ALTER TABLE warehouses
ADD COLUMN IF NOT EXISTS code VARCHAR(50),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS total_capacity INT DEFAULT 10000,
ADD COLUMN IF NOT EXISTS occupied_capacity INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_warehouses_code'
    ) THEN
        ALTER TABLE warehouses ADD CONSTRAINT uk_warehouses_code UNIQUE (code);
    END IF;
END $$;
