server.port=8080

spring.application.name=api-gateway
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=${AUTH_SERVICE_URL:http://omnistock-auth:8081}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.mvc.routes[1].id=admin-service
spring.cloud.gateway.mvc.routes[1].uri=${AUTH_SERVICE_URL:http://omnistock-auth:8081}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.mvc.routes[2].id=product-service
spring.cloud.gateway.mvc.routes[2].uri=${PRODUCT_SERVICE_URL:http://omnistock-product:8082}
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/products/**
spring.cloud.gateway.mvc.routes[3].id=inventory-service
spring.cloud.gateway.mvc.routes[3].uri=${INVENTORY_SERVICE_URL:http://omnistock-inventory:8083}
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.mvc.routes[4].id=order-service
spring.cloud.gateway.mvc.routes[4].uri=${ORDER_SERVICE_URL:http://omnistock-order:8084}
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[5]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}

jwt.secret=${JWT_SECRET:omnistock-super-secret-key-must-be-at-least-256-bits-long-for-hmacsha256}
